### ISSUE TITLE
pnpm-lock.yaml nested pattern makes TypeError

### ISSUE THREAD

**Issue by foolishell** [siketyan/loxcan#101]
# Issue
I'm using pnpm.
My pnpm-lock.yaml is like this:
```yaml
dependencies:
  next:
    specifier: ^13.4.6
    version: 13.4.6(@babel/core@7.22.5)(react-dom@18.2.0)(react@18.2.0)
  react:
    specifier: ^18.2.0
    version: 18.2.0
  react-dom:
    specifier: ^18.2.0
    version: 18.2.0(react@18.2.0)
```

Then, loxcan makes TypeError
```
PHP Fatal error:  Uncaught TypeError: Siketyan\Loxcan\Versioning\SemVer\SemVerVersionParser::parse(): Argument #1 ($version) must be of type string, array given, called in /home/runner/work/_actions/siketyan/loxcan/main/src/Scanner/Pnpm/PnpmLockParser.php on line 41 and defined in /home/runner/work/_actions/siketyan/loxcan/main/src/Versioning/SemVer/SemVerVersionParser.php:14
Stack trace:
#0 /home/runner/work/_actions/siketyan/loxcan/main/src/Scanner/Pnpm/PnpmLockParser.php(41): Siketyan\Loxcan\Versioning\SemVer\SemVerVersionParser->parse()
#1 /home/runner/work/_actions/siketyan/loxcan/main/src/Scanner/Pnpm/PnpmScanner.php(22): Siketyan\Loxcan\Scanner\Pnpm\PnpmLockParser->parse()
#2 /home/runner/work/_actions/siketyan/loxcan/main/src/UseCase/ScanUseCase.php(44): Siketyan\Loxcan\Scanner\Pnpm\PnpmScanner->scan()
#3 /home/runner/work/_actions/siketyan/loxcan/main/src/Command/ScanCommand.php(51): Siketyan\Loxcan\UseCase\ScanUseCase->scan()
#4 /home/runner/work/_actions/siketyan/loxcan/main/vendor/symfony/console/Command/Command.php(312): Siketyan\Loxcan\Command\ScanCommand->execute()
#5 /home/runner/work/_actions/siketyan/loxcan/main/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run()
#6 /home/runner/work/_actions/siketyan/loxcan/main/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#7 /home/runner/work/_actions/siketyan/loxcan/main/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#8 /home/runner/work/_actions/siketyan/loxcan/main/bin/loxcan(53): Symfony\Component\Console\Application->run()
#9 {main}
  thrown in /home/runner/work/_actions/siketyan/loxcan/main/src/Versioning/SemVer/SemVerVersionParser.php on line 14
```

## Why
This library expects only simple key value pattern like this:
```
dependencies:
  next: ^13.4.6
```
