### ISSUE TITLE
`latest` might not be working

### ISSUE THREAD

**Issue by yu-ichiro** [siketyan/loxcan#73]
I tried to install this on a repository as a GitHub Action like

```
steps:
  - uses: actions/checkout@v2
    with:
      fetch-depth: 0

  - uses: siketyan/loxcan@latest
```

as in the example, but got the following errors:

```
Current runner version: '2.285.0'
Operating System
Virtual Environment
Virtual Environment Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action `siketyan/loxcan@latest`, unable to find version `latest`
```

Maybe the latest tag is missing?
